[package]
name = "basic_3d"
version.workspace = true
edition.workspace = true

[dependencies]
rand = "0.10.0"
anyhow.workspace = true
cgmath.workspace = true
pretty_env_logger.workspace = true
kani_volcano_engine = { package = "kani-volcano-engine", path = "../../crates/engine" }
kani_volcano_math = { package = "kani-volcano-math", path = "../../crates/kani_volcano_math" }
kani_volcano_audio = { package = "kani-volcano-audio", path = "../../crates/kani_volcano_audio" }
winit.workspace = true
log.workspace=true
